### ISSUE TITLE
No useful stack trace on error

### ISSUE THREAD

**Issue by Ruuttu** [rgalanakis/dccautomation#3]
When there's an error inside a dccautomation.RemoteTestCase, I seem to get an opaque stack trace that doesn't point me to where the issue is.

```
----------------------------------------------------------------------
Traceback (most recent call last):
  File "..\dccautomation\testcase.py", line 72, in wrapped_test
    self._wrapped_test(client)
  File "..\dccautomation\testcase.py", line 103, in _wrapped_test
    client.exec_(formatted_str)
  File "..\dccautomation\client.py", line 108, in exec_
    return self.sendrecv(['exec', s])
  File "..\dccautomation\client.py", line 86, in sendrecv
    raise errtype(response['traceback'])
RuntimeError: Traceback (most recent call last):
  File "..\dccautomation\server.py", line 70, in start_server
    exec_context(exec_, arg)
ZeroDivisionError: integer division or modulo by zero
```

**Comment by rgalanakis** [comment]
Hi Ruutuu. Can you provide more information about your environment? Python version, and what app you're remote-ing into? Unfortunately it may be pretty difficult for me to debug this exactly because I don't have most dcc apps anymore (switched from games/vfx industry) but we may be able to repro this with a simple python-calling-python test case.
